### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by harsh204016** [InquisitiveMe15/SCRAPIE#4]
When running the application in local , getting this error:

` __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' not found.

Original exception:

ModuleNotFoundError: No module named 'config'`

**Comment by InquisitiveMe15** [comment]
Yeah, because it contains mine API passwords. I can't make it public.

For running the application you have to get your own credentials.

**Comment by harsh204016** [comment]
could you please provide the API address?

**Comment by InquisitiveMe15** [comment]
go to edamam api website, signup and get you credentials.

![image](https://user-images.githubusercontent.com/85685489/198838716-c1a168e2-4ba5-4c2b-88c8-830ac123d5eb.png)
